CREATE TABLE IF NOT EXISTS `GOODS`(
  `GID`INT UNSIGNED AUTO_INCREMENT,
  `GNAME`VARCHAR(200) NOT NULL,
  `GPRICE`FLOAT NOT NULL ,
  `GNUM`  INT NOT NULL,
  PRIMARY KEY (`GID`)
)ENGINE = InnoDB DEFAULT  CHARSET = utf8;
