CREATE TABLE IF NOT EXISTS `SALESMAN`(
  `SID`INT UNSIGNED AUTO_INCREMENT,
  `SPASSWORD`VARCHAR(200) NOT NULL,
  `SNAME`VARCHAR(200) NOT NULL ,
  PRIMARY KEY (`SID`)
)ENGINE = InnoDB DEFAULT  CHARSET = utf8;
